import { chromium, expect } from '@playwright/test';
import { servicesHub } from './services-hub';
import { disposableOrigin, workspacePage } from './test-origin';

const [source, usageSource] = process.argv.slice(2);
if (!source || !usageSource) throw new Error('Usage: bun scripts/test-services.ts <soma-checkout> <usage-hub-checkout>');
const url = process.env.IRIS_TEST_URL ?? 'http://iris-services.localhost:5198/workspace?review';
const origin = disposableOrigin(url);
const fixture = await servicesHub(source, usageSource, origin);
const other = await servicesHub(source, usageSource, origin);
const browser = await chromium.connectOverCDP(process.env.IRIS_TEST_CDP ?? 'http://127.0.0.1:9222');
try {
	const page = workspacePage(browser.contexts().flatMap(c => c.pages()), url);
	if (!page) throw new Error(`Open the dedicated test page: ${url}`);
	page.setDefaultTimeout(10000);
	await page.goto(new URL('/', url).href);
	const cdp = await page.context().newCDPSession(page);
	await cdp.send('Storage.clearDataForOrigin', { origin, storageTypes: 'all' });
	await cdp.detach();
	await page.goto(url);
	await page.getByRole('button', { name: 'Open my workspace', exact: true }).click();
	const notifications = page.getByRole('button', { name: /^Notifications/ });
	await expect(notifications).toBeVisible();
	await expect(notifications).toBeDisabled();
	await page.getByText('Connect to a hub', { exact: true }).click();await page.getByText('Use a device token', {exact:true}).click();
	await page.getByLabel('Hub address').fill(fixture.server.url.href.replace(/\/$/, ''));
	await page.getByLabel('Device token').fill('fixture');
	await page.getByRole('button',{name:'Connect',exact:true}).click();
	await expect(page.getByRole('button', { name: 'Fixture record', exact: true })).toBeVisible({ timeout: 30000 });
	await expect(notifications).toHaveAccessibleName('Notifications, 205 unread');
	await notifications.click();
	const dialog = page.getByRole('dialog');
	await expect(dialog.getByText('Example notice 205', { exact: true })).toBeVisible();
	await expect(dialog.getByText('Example notice 1', { exact: true })).toBeAttached();
	await dialog.getByRole('button', { name: 'Mark all read', exact: true }).click();
	await expect(notifications).toHaveAccessibleName('Notifications, 0 unread');
	expect(fixture.auth.db.query('SELECT count(*) AS n FROM _notifications WHERE read_at IS NULL').get()).toEqual({ n: 0 });
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByRole('button', { name: 'Settings', exact: true }).click();
	await expect(dialog.getByRole('heading', { name: 'Usage', exact: true })).toBeVisible();
	await expect(dialog.getByRole('rowheader', { name: 'Example device token', exact: true })).toBeVisible();
	const storage = dialog.getByRole('region', { name: 'D1 storage' });
	await expect(storage.getByText('Unmeasured', { exact: true })).toBeVisible();
	await expect(storage.getByRole('progressbar')).toHaveCount(0);
	await expect(dialog.getByRole('columnheader', { name: 'Storage' })).toHaveCount(0);
	await expect(dialog.getByRole('region', { name: 'D1 reads', exact: true }).getByText('1,234', { exact: true })).toBeVisible();
	await expect(dialog.getByRole('row', { name: /Example device/ })).toContainText('1,234');
	await expect(dialog.getByRole('region', { name: 'Requests', exact: true }).getByText('No hard cap', { exact: true })).toBeVisible();
	await expect(dialog.getByText(/Resets/)).toContainText(new Date(fixture.window.end).toLocaleDateString('en-US', { timeZone: 'UTC', year: 'numeric', month: 'short', day: 'numeric' }));
	// The hub still serves usage and notifications when a data-sync cap is reached.
	fixture.auth.db.query('UPDATE _usage SET rows_read=? WHERE principal=?').run(25e9, 'device:example');
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByRole('button', { name: 'Settings', exact: true }).click();
	await expect(dialog.getByRole('status')).toContainText('Sync is paused at the D1 reads cap.');
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByRole('button', { name: 'Connect', exact: true }).click();
	await expect(page.getByRole('alert')).toContainText('hub HTTP 429');
	await fixture.notify({ id: 'fixture:new', producer: 'another-producer', type: 'future.event', severity: 'warning', title: 'New event at the cap', body: 'The feed stays available.', data: { opaque: ['future'] } });
	await notifications.click();
	await expect(dialog.getByText('New event at the cap', { exact: true })).toBeVisible();
	await dialog.getByRole('article').filter({ has: page.getByRole('heading', { name: 'New event at the cap', exact: true }) }).getByRole('button', { name: /^Mark read/ }).click();
	await expect(notifications).toHaveAccessibleName('Notifications, 0 unread');
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByRole('button', { name: 'Settings', exact: true }).click();
	await expect(dialog.getByRole('status')).toContainText('Sync is paused');
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByLabel('Hub address').fill(other.server.url.href.replace(/\/$/, ''));
	await page.getByRole('button', { name: 'Connect', exact: true }).click();
	await expect(page.getByRole('alert').filter({ hasText: 'hub changed' })).toBeVisible();
	await page.getByRole('button', { name: 'Settings', exact: true }).click();
	await expect(dialog.getByText(fixture.server.url.origin, { exact: true })).toBeVisible();
	await expect(dialog.getByRole('status')).toContainText('Sync is paused');
	expect(other.requests.filter(r => r.authenticated)).toEqual([]);
	await page.setViewportSize({ width: 390, height: 844 });
	await page.emulateMedia({ colorScheme: 'dark' });
	expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
	await page.screenshot({ path: '/tmp/iris-usage-mobile.png' });
	await dialog.getByRole('button', { name: 'Close', exact: true }).click();
	await page.getByRole('button', { name: 'Switch workspace', exact: true }).click();
	await page.getByRole('button', { name: 'Try sample workspace', exact: true }).click();
	await expect(page.getByRole('button', { name: /^Notifications/ })).toHaveCount(0);
	console.log('PASS: paged notifications, authoritative shared mark-read, usage, unmeasured storage, device totals and workspace isolation');
} finally {
	await browser.close();
	await fixture.server.stop(true);
	await other.server.stop(true);
}
