import { chromium, expect } from '@playwright/test';
import { disposableOrigin } from './test-origin';

const url=process.env.LIFE_UI_TEST_URL??'http://life-ui-markdown.localhost:5198/workspace?review';
const origin=disposableOrigin(url);
const browser=await chromium.connectOverCDP(process.env.LIFE_UI_TEST_CDP??'http://127.0.0.1:9222');
try {
	const page=browser.contexts().flatMap(c=>c.pages()).find(p=>p.url()===url);
	if(!page)throw Error(`Open the dedicated test page: ${url}`);
	page.setDefaultTimeout(10000);
	await page.setViewportSize({ width: 1440, height: 1000 });
	page.setDefaultNavigationTimeout(10000);
	page.on('dialog', dialog => dialog.accept());
	await page.goto(new URL('/',url).href);
	const cdp=await page.context().newCDPSession(page);
	await cdp.send('Storage.clearDataForOrigin',{origin,storageTypes:'all'});
	await cdp.detach();
	await page.goto(url);
	await page.getByRole('button',{name:'Try sample workspace',exact:true}).click();
	await page.getByRole('button',{name:'New record',exact:true}).click();
	await page.getByRole('textbox',{name:'Title',exact:true}).fill('Rich editor check');
	const formatting=page.getByRole('toolbar',{name:'Body formatting',exact:true});
	await expect(formatting).toBeVisible();
	await formatting.getByRole('button',{name:'Heading 1',exact:true}).click();
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('An offline heading');
	await expect(page.getByRole('textbox',{name:'Body',exact:true}).getByRole('heading',{name:'An offline heading',level:1})).toBeVisible();
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Meta+a');
	await formatting.getByRole('button',{name:'Bold',exact:true}).click();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('# **An offline heading**\n');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('A paragraph');
	await page.getByRole('button',{name:'Body write',exact:true}).click();
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Meta+a');
	await formatting.getByRole('button',{name:'Italic',exact:true}).click();
	await formatting.getByRole('button',{name:'Link',exact:true}).click();
	await page.getByRole('textbox',{name:'Link URL',exact:true}).fill('https://example.com/reference');
	await page.getByRole('button',{name:'Apply link',exact:true}).click();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('*[A paragraph](https://example.com/reference)*\n');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('');
	await page.getByRole('button',{name:'Body write',exact:true}).click();
	await page.getByRole('textbox',{name:'Body',exact:true}).press('/');
	await page.getByRole('menu',{name:'Insert block',exact:true}).getByRole('menuitem',{name:'Heading 2',exact:true}).click();
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('A slash heading');
	await expect(page.getByRole('heading',{name:'A slash heading',level:2})).toBeVisible();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('## A slash heading\n');
	const original='# Kept exactly\n\n<mention-page url="https://example.com/page"/>\n\n- [ ] A task\n\n| A | B |\n| - | - |\n| one | two |\n';
	await page.getByRole('textbox',{name:'Body',exact:true}).fill(original);
	await page.getByRole('button',{name:'Body write',exact:true}).click();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	await page.getByRole('button',{name:'Save record',exact:true}).click();
	await expect(page.getByRole('button',{name:'Rich editor check',exact:true})).toBeVisible();
	await page.reload();
	await page.getByRole('button',{name:'Try sample workspace',exact:true}).click();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	// A record switch must discard the old editor's undo history.
	await page.getByRole('button', {name:'Close record',exact:true}).click();
	await page.getByRole('button', {name:'New record',exact:true}).click();
	await page.getByRole('textbox', {name:'Title',exact:true}).fill('Separate undo history');
	if (await page.getByRole('button',{name:'Body source',exact:true}).getAttribute('aria-pressed') !== 'true') await page.getByRole('button',{name:'Body source',exact:true}).click();
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('Text belonging only to the second record');
	await page.getByRole('button',{name:'Save record',exact:true}).click();
	await expect(page.getByRole('button',{name:'Separate undo history',exact:true})).toBeVisible();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await expect(page.getByRole('heading',{name:'Rich editor check',exact:true})).toBeVisible();
	await page.getByRole('button',{name:'Body write',exact:true}).click();
	await page.getByRole('toolbar',{name:'Body formatting',exact:true}).getByRole('button',{name:'Undo',exact:true}).click();
	await page.getByRole('button',{name:'Body source',exact:true}).click();
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	console.log('PASS: rich formatting, exact-source save/reopen and isolated undo history per record');
} finally {await browser.close();}
