import { workspacePage } from './test-origin';
import { chromium, expect } from '@playwright/test';

// Attach only to this task's already-created browser page (chrome-control).
const endpoint=process.env.LIFE_UI_TEST_CDP ?? 'http://127.0.0.1:9222';
const url=process.env.LIFE_UI_TEST_URL ?? 'http://127.0.0.1:5196/workspace';
const browser=await chromium.connectOverCDP(endpoint);
try {
  const page=workspacePage(browser.contexts().flatMap(c => c.pages()), url);
  if(!page) throw new Error(`Open the dedicated test page first: ${url}`);
  page.setDefaultTimeout(10_000);
  await page.setViewportSize({width:1200,height:900});
  await page.reload();
  await page.getByRole('button',{name:'Try sample workspace'}).click();
  await expect(page.getByRole('heading',{name:'notes',exact:true})).toBeVisible();
  const title=`Browser check ${Date.now()}`;
  await page.getByRole('button',{name:'New record',exact:true}).click();
  await page.getByRole('button',{name:'Save record',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText(/required/i);
  await page.getByRole('textbox', {name:'Title',exact:true}).fill(title);
  await page.getByLabel('Body', {exact:true}).fill('# Offline draft\n\nSaved as markdown.');
  await page.getByLabel('Related note',{exact:true}).selectOption({label:'A place to start'});
  await page.getByRole('button',{name:'Save record',exact:true}).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.reload();
  await page.getByRole('button',{name:'Try sample workspace'}).click();
  await page.getByLabel('Search records').fill(title);
  await page.getByRole('button',{name:title,exact:true}).click();
  await expect(page.getByLabel('Body',{exact:true})).toHaveValue('# Offline draft\n\nSaved as markdown.');
  await expect(page.getByLabel('Related note',{exact:true}).locator('option:checked')).toHaveText('A place to start');
  await page.getByLabel('Body',{exact:true}).fill('Unsaved text');
  page.once('dialog',dialog=>dialog.dismiss());
  await page.getByRole('button',{name:'Close record',exact:true}).click();
  await expect(page.getByLabel('Body',{exact:true})).toHaveValue('Unsaved text');
  await page.getByLabel('Body',{exact:true}).fill('# Offline draft\n\nSaved as markdown.');
  await page.getByRole('button',{name:'Move to trash',exact:true}).click();
  await expect(page.getByRole('button',{name:title,exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Trash',exact:true}).click();
  await page.getByRole('button',{name:title,exact:true}).click();
  await page.getByRole('button',{name:'Restore record',exact:true}).click();
  await page.getByRole('button',{name:'All records',exact:true}).click();
  await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();
  await page.getByLabel('Search records').fill(title);
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody tr')).toContainText('A place to start');
  await page.getByLabel('Filter property').selectOption('status');
  await page.getByLabel('Filter value').fill('Ready');
  await page.getByRole('button',{name:'Apply filter',exact:true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(0);
  await page.getByLabel('Filter value').fill('Draft');
  await page.getByRole('button',{name:'Apply filter',exact:true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.screenshot({path:'/tmp/life-ui-workspace-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/life-ui-workspace-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.emulateMedia({colorScheme:'dark'});
  await page.screenshot({path:'/tmp/life-ui-workspace-dark.png',fullPage:true});
  await page.emulateMedia({colorScheme:'light'});
  await page.getByRole('button',{name:'Table graph',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Table relationships'})).toBeVisible();
  await page.getByText('Group tables',{exact:true}).click();
  await page.getByLabel('Group for notes').fill('Writing');
  await page.getByLabel('Group for notes').blur();
  await expect(page.getByText('Writing',{exact:true})).toBeVisible();
  await page.screenshot({path:'/tmp/life-ui-graph.png',fullPage:true});
  await page.getByRole('button',{name:'Open table notes',exact:true}).click();
  await expect(page.getByRole('heading',{name:'notes',exact:true})).toBeVisible();
  console.log('PASS: validation, create, markdown, durable reload, trash, restore, search, mobile width');
} finally {await browser.close();}
