import { chromium, expect } from '@playwright/test';
import { disposableOrigin, workspacePage } from './test-origin';

const url=process.env.LIFE_UI_TEST_URL??'http://life-ui-markdown.localhost:5198/workspace?review';
const origin=disposableOrigin(url);
const browser=await chromium.connectOverCDP(process.env.LIFE_UI_TEST_CDP??'http://127.0.0.1:9222');
try {
	const page=workspacePage(browser.contexts().flatMap(c => c.pages()), url);
	if(!page)throw Error(`Open the dedicated test page: ${url}`);
	page.setDefaultTimeout(10000);
	await page.setViewportSize({ width: 1440, height: 1000 });
	page.setDefaultNavigationTimeout(10000);
	page.on('dialog', dialog => dialog.accept());
	await page.goto(new URL('/',url).href);
	const cdp=await page.context().newCDPSession(page);
	await cdp.send('Storage.clearDataForOrigin',{origin,storageTypes:'all'});
	await cdp.detach();
	await page.goto(url);
	await page.waitForLoadState('networkidle');
	await page.getByRole('button',{name:'Try sample workspace',exact:true}).click();
	await page.getByRole('button',{name:'New record',exact:true}).click();
	await page.getByRole('textbox',{name:'Title',exact:true}).fill('Rich editor check');
	async function mode(mode: 'source' | 'write') {
		if (await page.locator('textarea[aria-label="Body"]').isVisible() === (mode === 'source')) return;
		await page.getByRole('button', {name:'Body options',exact:true}).click();
		await page.getByRole('menuitem', {name:`Body ${mode}`,exact:true}).click();
	}
	const formatting=page.getByRole('toolbar',{name:'Body formatting',exact:true});
	await expect(page.locator('.ProseMirror')).toBeVisible();
	await expect(formatting, 'Formatting controls appear only for selected text').toBeHidden();
	await expect(page.locator('.markdown-editor button:visible')).toHaveCount(1);
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('# ');
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('An offline heading');
	await expect(page.getByRole('textbox',{name:'Body',exact:true}).getByRole('heading',{name:'An offline heading',level:1})).toBeVisible();
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Meta+a');
	await formatting.getByRole('button',{name:'Bold',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('# **An offline heading**\n');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('');
	await mode('write');
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('- First item');
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Enter');
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('Second item');
	await expect(page.locator('.ProseMirror ul li')).toHaveText(['First item', 'Second item']);
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Enter');
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Enter');
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('Outside the list');
	await expect(page.locator('.ProseMirror > p')).toHaveText('Outside the list');
	await expect(formatting).toBeHidden();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('* First item\n* Second item\n\nOutside the list\n');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('A paragraph');
	await mode('write');
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Meta+a');
	await formatting.getByRole('button',{name:'Italic',exact:true}).click();
	await formatting.getByRole('button',{name:'Link',exact:true}).click();
	await page.getByRole('textbox',{name:'Link URL',exact:true}).fill('https://example.com/reference');
	await page.getByRole('button',{name:'Apply link',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('*[A paragraph](https://example.com/reference)*\n');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('');
	await mode('write');
	await page.getByRole('textbox',{name:'Body',exact:true}).press('/');
	const blocks=page.getByRole('menu',{name:'Insert block',exact:true});
	await expect(blocks.getByRole('menuitem',{name:'Heading 1',exact:true})).toBeFocused();
	await page.keyboard.press('ArrowDown');
	await expect(blocks.getByRole('menuitem',{name:'Heading 2',exact:true})).toBeFocused();
	await page.keyboard.press('Enter');
	await page.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('A slash heading');
	await expect(page.getByRole('heading',{name:'A slash heading',level:2})).toBeVisible();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('## A slash heading\n');
	const original='# Kept exactly\n\n<mention-page url="https://example.com/page"/>\n\n- [ ] A task\n\n| A | B |\n| - | - |\n| one | two |\n';
	await page.getByRole('textbox',{name:'Body',exact:true}).fill(original);
	await mode('write');
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	await page.getByRole('button',{name:'Save record',exact:true}).click();
	await expect(page.getByRole('button',{name:'Rich editor check',exact:true})).toBeVisible();
	await page.reload();
	await page.getByRole('button',{name:'Try sample workspace',exact:true}).click();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	// A record switch must discard the old editor's undo history.
	await page.getByRole('button', {name:'Close record',exact:true}).click();
	await page.getByRole('button', {name:'New record',exact:true}).click();
	await page.getByRole('textbox', {name:'Title',exact:true}).fill('Separate undo history');
	await mode('source');
	await page.getByRole('textbox',{name:'Body',exact:true}).fill('Text belonging only to the second record');
	await page.getByRole('button',{name:'Save record',exact:true}).click();
	await expect(page.getByRole('button',{name:'Separate undo history',exact:true})).toBeVisible();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await expect(page.getByRole('heading',{name:'Rich editor check',exact:true})).toBeVisible();
	await mode('write');
	await page.getByRole('button',{name:'Body options',exact:true}).click();
	await page.getByRole('menuitem',{name:'Undo',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	await page.setViewportSize({width:320,height:640});
	await mode('write');
	await page.getByRole('textbox',{name:'Body',exact:true}).press('Meta+a');
	await expect(formatting).toBeVisible();
	const bounds=await formatting.boundingBox();
	expect(bounds!.x).toBeGreaterThanOrEqual(0);
	expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(320);
	await page.getByRole('textbox',{name:'Body',exact:true}).press('ArrowRight');
	await expect(formatting).toBeHidden();
	// Escape dismisses Markdown popups before the containing grid can save the cell.
	await page.setViewportSize({width:1440,height:1000});
	await page.getByRole('button',{name:'Close record',exact:true}).click();
	const columns=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^\s*Columns\s*$/})});
	await columns.locator('summary').click();
	await columns.getByRole('checkbox',{name:'Show Body',exact:true}).check();
	await columns.locator('summary').click();
	const grid=page.getByRole('grid',{name:'Records',exact:true});
	const row=grid.getByRole('row').filter({has:page.getByRole('button',{name:'Rich editor check',exact:true})});
	const cell=row.locator('[data-column="body"]');
	await cell.focus();
	await cell.press('Enter');
	const inline=page.getByRole('group',{name:'Edit Body',exact:true});
	await expect(inline).toBeVisible();
	await mode('source');
	await inline.getByRole('textbox',{name:'Body',exact:true}).fill('');
	await mode('write');
	await inline.getByRole('textbox',{name:'Body',exact:true}).press('/');
	await expect(page.getByRole('menu',{name:'Insert block',exact:true})).toBeVisible();
	await page.keyboard.press('Tab');
	await expect(page.getByRole('menuitem',{name:'Heading 2',exact:true}), 'Tab stays within the block menu without saving the cell').toBeFocused();
	await page.keyboard.press('Escape');
	await expect(page.getByRole('menu',{name:'Insert block',exact:true})).toBeHidden();
	await expect(inline, 'Closing the slash menu must keep the unsaved cell open').toBeVisible();
	await expect(inline.getByRole('textbox',{name:'Body',exact:true})).toBeFocused();
	await inline.getByRole('textbox',{name:'Body',exact:true}).pressSequentially('Draft after closing the menu');
	await inline.getByRole('button',{name:'Body options',exact:true}).click();
	await page.keyboard.press('Escape');
	await expect(inline).toBeVisible();
	await expect(inline.getByRole('button',{name:'Body options',exact:true})).toBeFocused();
	await inline.getByRole('button',{name:'Discard',exact:true}).click();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(original);
	await page.getByRole('button',{name:'Close record',exact:true}).click();
	await cell.focus();
	await cell.press('Enter');
	await mode('source');
	await inline.getByRole('textbox',{name:'Body',exact:true}).fill('# Saved from the cell\n');
	await inline.getByRole('textbox',{name:'Body',exact:true}).press('Escape');
	await expect(inline, 'Escape without an open popup still saves the cell').toBeHidden();
	await page.getByRole('button',{name:'Rich editor check',exact:true}).click();
	await mode('source');
	await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue('# Saved from the cell\n');
	console.log('PASS: rich formatting, exact-source save/reopen and isolated undo history per record');
} finally {await browser.close();}
