import { chromium, expect } from '@playwright/test';
import { regressionHub } from './workspace-regression-hub';
import { disposableOrigin, workspacePage } from './test-origin';

const url=process.env.LIFE_UI_TEST_URL??'http://life-ui-markdown.localhost:5252/workspace?review';
const origin=disposableOrigin(url), source=process.argv[2];
if(!source)throw Error('Provide the life-data checkout');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAUAAAAB4CAIAAAAMrLyJAAACk0lEQVR4nO3TQQ2AQBAEwZXFH8uowAA2kICMSx+VjIGapOd63iU7j3vJeHl38s7fwLy8O3kFzMsb9gqYlzfsFTAvb9grYF7esFfAvLxhr4B5ecNeAfPyhr0C5uUNewXMyxv2CpiXN+wVMC9v2CtgXt6wV8C8vGGvgHl5w14B8/KGvQLm5Q17BczLG/YKmJc37BUwL2/YK2Be3rBXwLy8Ya+AeXnDXgHz8oa9AublDXsFzMsb9gqYlzfsFTAvb9grYF7esFfAvLxhr4B5ecNeAfPyhr0C5uUNewXMyxv2CpiXN+wVMC9v2CtgXt6wV8C8vGGvgHl5w95xNC9v1ytgXt6wV8C8vGGvgHl5w14B8/KGvQLm5Q17BczLG/YKmJc37BUwL2/YK2Be3rBXwLy8Ya+AeXnDXgHz8oa9AublDXsFzMsb9gqYlzfsFTAvb9grYF7esFfAvLxhr4B5ecNeAfPyhr0C5uUNewXMyxv2CpiXN+wVMC9v2CtgXt6wV8C8vGGvgHl5w14B8/KGvQLm5Q17BczLG/YKmJc37BUwL2/YK2Be3rBXwLy8Ya+AeXnDXgHz8oa9AublDXsFzMsb9gqYlzfsHUfz8na9AublDXsFzMsb9gqYlzfsFTAvb9grYF7esFfAvLxhr4B5ecNeAfPyhr0C5uUNewXMyxv2CpiXN+wVMC9v2CtgXt6wV8C8vGGvgHl5w14B8/KGvQLm5Q17BczLG/YKmJc37BUwL2/YK2Be3rBXwLy8Ya+AeXnDXgHz8oa9AublDXsFzMsb9gqYlzfsFTAvb9grYF7esFfAvLxhr4B5ecNeAfPyhr0C5uUNewXMyxv2CpiXN+wVMC9v2CtgXt6wV8C8vGGvgHl5w94PCbtQeLqWgEIAAAAASUVORK5CYII=','base64');
const requests:string[]=[];
let missing=true;
const archive={async get(key:string){
  requests.push(key);
  if(key==='raw/missing.png' && missing)return null;
  const image=key.endsWith('.png'), bytes=image?png:Buffer.from('Retained document bytes');
  return {body:bytes,size:bytes.length,writeHttpMetadata(headers:Headers){headers.set('Content-Type',image?'image/png':'text/plain');}};
}};
const {server,db,auth}=await regressionHub(source,origin,0,{env:{ARCHIVE:archive}});
const sourceID='11111111222233334444555555555555';
const sourceURL=`https://app.notion.com/p/Related-${sourceID}`;
const body=`# Retained content\n\n![Diagram](/v1/files/raw/diagram.png)\n\n![Retry diagram](/v1/files/raw/missing.png)\n\n![External image](https://expired.invalid/image.png)\n\n[Document](/v1/files/raw/document.txt)\n\n[Related record](${sourceURL})\n`;
db.db.query('UPDATE widgets SET body=? WHERE id=?').run(body,'fixture-record');
const ddl='CREATE TABLE provenance (id TEXT PRIMARY KEY,from_kind TEXT,from_ref TEXT,to_kind TEXT,to_ref TEXT,rel TEXT,field TEXT,created_at TEXT,updated_at TEXT,deleted_at TEXT,hub_at TEXT)';
db.db.exec(ddl);db.db.query('INSERT INTO _schema_log(applied_at,ddl) VALUES (?,?)').run(new Date().toISOString(),ddl);
db.db.query('INSERT INTO catalog_tables(id,kind,display) VALUES (?,?,?)').run('provenance','system','id');
db.db.query('INSERT INTO provenance(id,from_kind,from_ref,to_kind,to_ref,rel,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run('fixture-source','notion',sourceID,'widgets','second-record','imported_from',new Date().toISOString(),new Date().toISOString());
const browser=await chromium.connectOverCDP(process.env.LIFE_UI_TEST_CDP??'http://127.0.0.1:9222');
let ownedPage:import('@playwright/test').Page|undefined;
try{
  const page=ownedPage=workspacePage(browser.contexts().flatMap(c=>c.pages()),url);
  if(!page)throw Error('Open the reserved review page');
  page.setDefaultTimeout(10000);await page.setViewportSize({width:1440,height:1000});
  const externalRequests:string[]=[];page.on('request',request=>{if(request.url().includes('expired.invalid'))externalRequests.push(request.url());});
  await page.goto(new URL('/',url).href);
  const cdp=await page.context().newCDPSession(page);await cdp.send('Storage.clearDataForOrigin',{origin,storageTypes:'all'});await cdp.detach();
  await page.goto(url);await page.getByRole('button',{name:'Open my workspace',exact:true}).click();
  await page.getByText('Connect to a hub',{exact:true}).click();await page.getByText('Use a device token',{exact:true}).click();
  await page.getByLabel('Hub address').fill(server.url.href.replace(/\/$/,''));await page.getByLabel('Device token').fill('fixture');
  await page.getByRole('button',{name:'Sync now',exact:true}).click();
  await page.getByRole('navigation',{name:'Tables'}).getByRole('button',{name:'widgets',exact:true}).click();
  await page.getByRole('button',{name:'Fixture record',exact:true}).click();
  await expect(page.locator('[data-type="retained-image"] img[alt="Diagram"]')).toBeVisible();
  await expect.poll(()=>page.locator('img[alt="Diagram"]').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBe(320);
  await expect(page.getByText(/Retry diagram: File HTTP 404/)).toBeVisible();
  missing=false;await page.getByRole('button',{name:'Retry image',exact:true}).click();
  await expect(page.locator('[data-type="retained-image"] img[alt="Retry diagram"]')).toBeVisible();
  expect(externalRequests).toEqual([]);
  await page.getByRole('button',{name:'Body source',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Body',exact:true})).toHaveValue(body);
  await page.getByRole('button',{name:'Body write',exact:true}).click();
  await page.getByRole('link',{name:'Document',exact:true}).click();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download file',exact:true}).click();
  const file=await download;expect(file.suggestedFilename()).toBe('document.txt');
  const downloaded=await file.path();if(!downloaded)throw Error('Download unavailable');
  expect(await Bun.file(downloaded).text()).toBe('Retained document bytes');await file.delete();
  await page.getByRole('link',{name:'Related record',exact:true}).click();
  await expect(page.getByRole('link',{name:'Open original link',exact:true})).toHaveAttribute('href',sourceURL);
  await page.getByRole('button',{name:'Open in workspace',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Second record',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close record',exact:true}).click();
  await page.getByRole('button',{name:'Fixture record',exact:true}).click();
  await expect(page.locator('img[alt="Diagram"]')).toBeVisible();
  await page.getByRole('button',{name:'Sync now',exact:true}).click();
  await expect(page.getByRole('button',{name:'Sync now',exact:true})).toBeEnabled();
  expect((db.db.query('SELECT body FROM widgets WHERE id=?').get('fixture-record') as any).body).toBe(body);
  expect(requests).toContain('raw/document.txt');
  if(process.env.LIFE_UI_TEST_SCREENSHOT)await page.screenshot({path:process.env.LIFE_UI_TEST_SCREENSHOT,fullPage:true});
  console.log('PASS: authenticated inline images, retry, exact-source reopen, download and provenance-backed record navigation');
}catch(error){console.error(await ownedPage?.locator('body').innerText());throw error;}finally{await ownedPage?.goto(new URL('/',url).href).catch(()=>{});await browser.close();server.stop(true);db.db.close();auth.db.close();}
